/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILE_H_RPCGEN
#define _FILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define FILE_PROG 0x31234567
#define FILE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SERVEFILE 1
extern  char ** servefile_1(char **, CLIENT *);
extern  char ** servefile_1_svc(char **, struct svc_req *);
extern int file_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SERVEFILE 1
extern  char ** servefile_1();
extern  char ** servefile_1_svc();
extern int file_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILE_H_RPCGEN */
